version: '3'

services:
  pgsql:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'order'
    restart: always
    volumes:
      - pg-data:/var/lib/postgressql/data
    environment:
      POSTGRES_USER: order
      POSTGRES_PASSWORD: pgpassword

volumes:
  pg-data: